baseURL: "https://blog.ziying.site/"
title: 士子☀️的博客
paginate: 15

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

languageCode: "zh"
defaultContentLanguage: "zh"
defaultContentLanguageInSubdir: true

params:
  env: development
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [ Blog, 士子☀的博客, 曹儒士子, 博客, 个人博客 ]
  author: 士子☀
  DateFormat: "2006年01月02日"
  defaultTheme: auto
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  searchHidden: false

  assets:
    favicon: "/favicon.ico"

  label:
    text: "士子☀的博客"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

  profileMode:
    enabled: false

taxonomies:
  tag: tags
  category: categories
  series: series

menu:
  main:
    - identifier: index
      name: 首页
      url:
      weight: 10
    - identifier: search
      name: 搜索
      url: search
      weight: 30
    - identifier: archives
      name: 时间轴
      url: archives
      weight: 40
    - identifier: about
      name: 关于
      url: about
      weight: 50
