name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 将 master 分支检出
        uses: actions/checkout@v2
      - name: 测试当前所处的文件夹
        run: pwd
      - name: 安装 Ruby 2.6
          uses: actions/setup-ruby@v1
          with:
            ruby-version: 2.6
              - name: 使用 gem 安装 github-pages
                run: gem install github-pages
      - name: 构建静态文件
        run: jekyll build
      - name: 列出所有文件
        run: cd _site && ls -a
