name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 将 master 分支检出
        uses: actions/checkout@v2
      - name: 测试当前所处的文件夹
        run: pwd
      - name: 安装 Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: 使用 gem 安装 github-pages
        run: gem install github-pages
      - name: 构建静态文件
        run: jekyll build
      - name: 列出目录文件
        run: ls
      - name: 下载 qshell 可执行文件
        run: |
          wget http://devtools.qiniu.com/qshell-linux-x64-v2.4.1.zip?ref=developer.qiniu.com -O qshell.zip
          unzip qshell.zip | mv `unzip -l qshell.zip | awk '{if(NR == 4){ print $4}}'` qshell
      - name: 列出目录文件
        run: ls

