name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 将 master 分支检出
      uses: actions/checkout@v2
    - name: test
      run: pwd
    - name: 使用 github-pages
      run: gem install github-pages
    - name: 构建静态文件
      run: jekyll build
    - name: 列出所有文件
      run: cd _site && ls -a
