name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-qshell:
    runs-on: ubuntu-latest
    steps:
      - name: 将 qshell 源码检出
        uses: actions/checkout@v2
        with:
          repository: 'qiniu/qshell'
          ref: 'v2.4.0'
      - name: 安装 Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: 构建 qshell
        run: go build main.go
      - name: 添加 artifact
        uses: actions/upload-artifact@v2
        with:
          name: qshell
          path: main
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 将 master 分支检出
        uses: actions/checkout@v2
      - name: 测试当前所处的文件夹
        run: pwd
      - name: 安装 Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: 使用 gem 安装 github-pages
        run: gem install github-pages
      - name: 构建静态文件
        run: jekyll build
      - name: 列出目录文件
        run: ls
      - name: 将 _site 文件夹重命名为 site ，并压缩该文件夹
        run: mv _site site && zip -r site site
      - name: 添加 artifact
        uses: actions/upload-artifact@v2
        with:
          name: site.zip
          path: site.zip
  deploy:
    needs: [build-qshell, build]
    runs-on: ubuntu-latest
    steps:
      - name: 下载生成的 qshell
        uses: actions/download-artifact@v2
        with:
          name: qshell
          path: qshell
      - name: 下载生成的静态文件
        uses: actions/download-artifact@v2
        with:
          name: site.zip
          path: site.zip
      - name: 将网站静态文件解压
        run: ls -a && unzip ./site
      - name: 列出所有文件
        run: ls
      - name: 使用 qshell 执行上传命令
        run: |
          qshell account ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} blogfile
          qshell listbucket zy-blogfile -o zy-blogfile.list.txt
          cat zy-blogfile.list.txt
          qshell qupload2 --src-dir=./site --bucket=zy-blogfile

