name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-qshell:
    runs-on: ubuntu-latest
    steps:
      - name: 将 qshell 源码检出
        uses: actions/checkout@v2
        with:
          repository: 'qiniu/qshell'
          ref: 'v2.4.0'
      - name: 安装 Go 1.13.1
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: 构建 qshell
        run: go build main.go
      - name: 添加 artifact
        uses: actions/upload-artifact@v2
        with:
          name: qshell
          path: main
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 将 master 分支检出
        uses: actions/checkout@v2
      - name: 测试当前所处的文件夹
        run: pwd
      - name: 安装 Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: 使用 gem 安装 github-pages
        run: gem install github-pages
      - name: 构建静态文件
        run: jekyll build
      - name: 列出目录文件
        run: ls
      - name: 压缩 _site 文件夹
        run: zip -r site.zip _site
      - name: 添加 artifact
        uses: actions/upload-artifact@v2
        with:
          name: site.zip
          path: site.zip
  deploy:
    needs: [build-qshell, build]
    runs-on: ubuntu-latest
    steps:
      - name: 下载生成的 qshell
        uses: actions/download-artifact@v2
        with:
          name: qshell
          path: qshell
      - name: 下载生成的静态文件
        uses: actions/download-artifact@v2
        with:
          name: site.zip
          path: site.zip
      - name: 列出目录文件
          run: ls

