name: 将博客自动部署到七牛云

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 将 master 分支检出
        uses: actions/checkout@v2
      - name: 下载 qshell 工具
        run: sh ./scripts/qshell.sh
      - name: 打包网站代码
        run: ./hugo -D
      - name: 将 404 文件修改
        run: mv ./public/404.html ./public/errno-404
      - name: 使用 qshell 执行上传命令
        run: sh ./scripts/deploy.sh ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }}
